enabled: true
fullnameOverride: apisix-etcd
image:
  registry: artifact.onwalk.net/public
  repository: apisix/etcd-adapter
  tag: latest
service:
  name: ""  # 如果为空，将使用fullnameOverride的值作为服务名称
  port: 2379
  tag: latest
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi
mysql:
  host: 127.0.0.1
  port: 3306
  username: apisix
  password: apisix
  database: apisix
