apiVersion: apps/v1
kind: Deployment
metadata:
  name: windmill-app
  labels:
    app: windmill-app
    app.kubernetes.io/name: windmill-app
    chart: {{ template "windmill.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.windmill.appReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: windmill-app
  template:
    metadata:
      labels:
        app: windmill-app
        app.kubernetes.io/name: windmill-app
        release: {{ .Release.Name }}
{{- with .Values.windmill.app.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.windmill.app.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      terminationGracePeriodSeconds: 40
      serviceAccountName: {{ template "windmill.serviceAccountName" . }}
      {{ if .Values.windmill.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.windmill.imagePullSecrets }}
      {{ end }}
      {{ if .Values.windmill.app.initContainers}}
      initContainers:
      {{- with .Values.windmill.app.initContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{ end }}
      containers:
      {{- with .Values.windmill.app.extraContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      - name: windmill-app
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 30"]
        {{ if .Values.enterprise.enabled }}
        image: {{ default "ghcr.io/windmill-labs/windmill-ee" .Values.windmill.image }}:{{ default .Chart.AppVersion .Values.windmill.tag }}
        {{ else }}
        image: {{ default "ghcr.io/windmill-labs/windmill" .Values.windmill.image }}:{{ default .Chart.AppVersion .Values.windmill.tag }}
        {{ end }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8001
        readinessProbe:
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            host:
            scheme: HTTP
            path: /
            httpHeaders:
            - name: Host
              value: localhost
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        {{- with .Values.windmill.app.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{ if .Values.enterprise.enabled }}
        - name : "METRICS_ADDR"
          value: "true"
        {{ end }}
        {{ if .Values.windmill.databaseUrlSecretName }}
        - name: "DATABASE_URL"
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.windmill.databaseUrlSecretName }}"
              key: "{{ .Values.windmill.databaseUrlSecretKey }}"
        {{ else }}
        - name: "DATABASE_URL"
          value: "{{ .Values.windmill.databaseUrl }}"
        {{ end }}
        - name: "BASE_URL"
          value: "{{ .Values.windmill.baseProtocol }}://{{ .Values.windmill.baseDomain }}"
        - name: "RUST_LOG"
          value: "{{ .Values.windmill.rustLog }}"
        - name: "MODE"
          value: "server"
        - name: "JSON_FMT"
          value: "true"
        {{ if .Values.windmill.instanceEventsWebhook }}
        - name: "INSTANCE_EVENTS_WEBHOOK"
          value: "true"
        {{ end }}
        {{ if .Values.enterprise.enabled }}
        - name: "LICENSE_KEY"
          value: "{{ .Values.enterprise.licenseKey }}"
        {{ end }}
        {{ if .Values.enterprise.samlMetadata }}
        - name: "SAML_METADATA"
          value: "{{ .Values.enterprise.samlMetadata }}"
        {{ end }}
        {{if .Values.enterprise.scimTokenSecretName}}
        - name: "SCIM_TOKEN"
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.enterprise.scimTokenSecretName }}"
              key: "{{ .Values.enterprise.scimTokenSecretKey }}"
        {{ else if .Values.enterprise.scimToken}}
        - name: "SCIM_TOKEN"
          value: "{{ .Values.enterprise.scimToken }}"
        {{ end }}
        {{ if .Values.windmill.openaiAzureBasePath}}
        - name: OPENAI_AZURE_BASE_PATH
          value: "{{ .Values.windmill.openaiAzureBasePath }}"
        {{ end }}
        resources:
{{ toYaml .Values.windmill.app.resources | indent 12 }}
{{- with .Values.windmill.app.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.app.volumes }}
      volumes:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.app.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.app.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.app.securityContext }}
      securityContext:
{{ toYaml . | indent 12 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: windmill-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: windmill-app
  sessionAffinity: ClientIP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: windmill-app-metrics
  labels:
    operated-prometheus: "true"
spec:
  clusterIP: None
  ports:
  - port: 8001
    name: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: windmill-app
  sessionAffinity: None
  type: ClusterIP
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: windmill-app
#   labels:
#     instance: primary
# spec:
#   selector:
#     matchLabels:
#       app: windmill-app-metrics
#   endpoints:
#   - port: metrics
#     interval: 30s
#     path: /metrics
