{{- if .Values.enterprise.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windmill-multiplayer
  labels:
    app: windmill-multiplayer
    app.kubernetes.io/name: windmill-multiplayer
    chart: {{ template "windmill.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.windmill.multiplayerReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: windmill-multiplayer
  template:
    metadata:
      labels:
        app: windmill-multiplayer
        app.kubernetes.io/name: windmill-multiplayer
        container: windmill-multiplayer
{{- with .Values.windmill.multiplayer.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.windmill.multiplayer.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
  {{- end }}
    spec:
      {{ if .Values.windmill.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.windmill.imagePullSecrets }}
      {{ end }}  
      containers:
      - name: windmill-multiplayer
        image: {{ default "ghcr.io/windmill-labs/windmill-multiplayer" .Values.windmill.multiplayer.image }}:{{ default "latest" .Values.windmill.multiplayer.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        resources:
{{ toYaml .Values.windmill.multiplayer.resources | indent 12 }}
    {{- with .Values.windmill.multiplayer.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.multiplayer.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.multiplayer.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }} 
    {{- with .Values.windmill.multiplayer.securityContext }}
      securityContext:
{{ toYaml . | indent 12 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: windmill-multiplayer
spec:
  ports:
    - port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app.kubernetes.io/name: windmill-multiplayer
  sessionAffinity: ClientIP
  type: ClusterIP
{{- end -}}
