{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.service.name }}{{ .Values.service.name }}{{ else }}{{ .Values.fullnameOverride }}{{ end }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ if .Values.service.name }}{{ .Values.service.name }}{{ else }}{{ .Values.fullnameOverride }}{{ end }}
{{- end }}
