apiVersion: apps/v1
kind: Deployment
metadata:
  name: windmill-lsp
  labels:
    app: windmill-lsp
    app.kubernetes.io/name: windmill-lsp
    chart: {{ template "windmill.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  replicas: {{ .Values.windmill.lspReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: windmill-lsp
  template:
    metadata:
      labels:
        app: windmill-lsp
        app.kubernetes.io/name: windmill-lsp
        container: windmill-lsp
{{- with .Values.windmill.lsp.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.windmill.lsp.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      {{ if .Values.windmill.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.windmill.imagePullSecrets }}
      {{ end }}       
      containers:
      - name: windmill-lsp
        image: {{ default "ghcr.io/windmill-labs/windmill-lsp" .Values.windmill.lsp.image }}:{{ default "latest" .Values.windmill.lsp.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        {{- with .Values.windmill.lsp.extraEnv }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
{{ toYaml .Values.windmill.lsp.resources | indent 12 }}
    {{- with .Values.windmill.lsp.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.lsp.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.lsp.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.lsp.securityContext }}
      securityContext:
{{ toYaml . | indent 12 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: windmill-lsp
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app.kubernetes.io/name: windmill-lsp
  sessionAffinity: ClientIP
  type: ClusterIP
