name: Sync Chart From Upstream Repo

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
  push:
    paths:
      - '.github/workflows/sync-charts.yaml'
  workflow_dispatch:
    branches:
      - main

env:
  REPO_URL: https://github.com/open-source-solution-design/MicroService.git 
  REPO_BRANCH: main
  TZ: Asia/Shanghai
  TAG: 0.1.4 

jobs:
  build-push-charts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initialization environment
      shell: bash
      run: |
        sudo apt update
        sudo apt install git -y
        git config user.name shenlan
        git config user.email manbuzhe2009@qq.com
        sudo curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm plugin install https://github.com/chartmuseum/helm-push.git
        helm repo add sync https://charts.onwalk.net
        helm repo add fluxcd https://fluxcd-community.github.io/helm-charts
        helm repo up

    - name: Fetch & push charts
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/
        rm -rvf flux2
        helm fetch fluxcd/flux2 --version 2.12.1 --untar
        cd flux2 && helm cm-push -u admin -p "${{ secrets.HELM_REPO_PASSWORD }}" --force ./ sync
